name: Auto Commit

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%S%z'`
          echo $d > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "lienhartcharles@gmail.com@users.noreply.github.com"
          git config --local user.name "bluffblue"
          git add -A
          git commit -m "🤖 Auto Update at: $(date '+%Y-%m-%d %H:%M:%S')"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
